apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: freskimaliu/multi-worker
        env:
          - name: REDIS_HOST
            value: redis-cluter-ip-service
          - name: REDIS_PORT
            value: '6379'
